steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Compile pipeline
  - name: 'python'
    entrypoint: 'python'
    args: ['cicd_vertexai_updated.py']
    id: 'compile'

  # Upload compiled pipeline to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'xgb_pipe.json', 'gs://vertextestingpipeline/compiledpipeline']
    id:  'upload'
    waitFor: ['compile']

  # Run pipeline
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['pubsub', 'topics', 'publish', 'vertexmessage', '--message', 'hello']
    id:  'run'
