steps:
  # Install dependencies
  - name: python
    entrypoint: pip
    args: ["install", "-r", "requirements.txt", "--user"]

  # Compile pipeline
  - name: 'python'
    entrypoint: 'python'
    args: ['ci_pipeline.py']
    id: 'compile'

  # Upload compiled pipeline to GCS.
  - name: 'gcr.io/cloud-builders/gsutil'
    args: ['cp', 'xgb_pipe.json', 'gs://datasetfiles']
    id:  'upload'
    waitFor: ['compile']

# Run pipeline
 - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    args: ['gcloud','pubsub', 'topics', 'publish','cicdtesting','--message','hello']
    id:  'run'
